ERROR    root:init_helpers.py:90 Failed to capture screenshot: [Errno 2] No such file or directory: 'data/attachments/dev_chrome_130.0.6723.58_entered_batch_number.png'
ERROR    root:init_helpers.py:90 Failed to capture screenshot: [Errno 2] No such file or directory: 'data/attachments/dev_chrome_130.0.6723.58_batch_already_added_warning_message_exists.png'