INFO     root:conftest.py:48 EDGE browser version is : 131.0.2903.48
DEBUG    pytest_bdd.scenario:scenario.py:146 Adding providers for fixture 'pytestbdd_stepimpl_given_I am on the find a patient by demographics page': [<FixtureDef argname='pytestbdd_stepdef_given_I am on the find a patient by demographics page' scope='function' baseid='tests/test_find_a_patient_steps.py'>]
DEBUG    pytest_bdd.scenario:scenario.py:146 Adding providers for fixture 'pytestbdd_stepimpl_when_I click the search button': [<FixtureDef argname='pytestbdd_stepdef_when_I click the search button' scope='function' baseid='tests/test_find_a_patient_steps.py'>, <FixtureDef argname='pytestbdd_stepdef_when_I click the search button_1' scope='function' baseid='tests/test_find_a_patient_steps.py'>]
DEBUG    pytest_bdd.scenario:scenario.py:146 Adding providers for fixture 'pytestbdd_stepimpl_then_I can see a first name error message Enter the first name': [<FixtureDef argname='pytestbdd_stepdef_then_I can see a first name error message {errorMessage}' scope='function' baseid='tests/test_find_a_patient_steps.py'>]
DEBUG    root:init_helpers.py:102 Directory verified: /app/data/attachments
DEBUG    root:init_helpers.py:108 Saving screenshot to: /app/data/attachments/qa_edge_131.0.2903.48_error_message_appears_for_first_name.png
DEBUG    root:playwrightHelper.py:89 Scrolling to the top of the page.
DEBUG    root:init_helpers.py:114 Screenshot attached at: /app/data/attachments/qa_edge_131.0.2903.48_error_message_appears_for_first_name.png
DEBUG    pytest_bdd.scenario:scenario.py:146 Adding providers for fixture 'pytestbdd_stepimpl_then_I can see a last name error message Enter the last name': [<FixtureDef argname='pytestbdd_stepdef_then_I can see a last name error message {errorMessage}' scope='function' baseid='tests/test_find_a_patient_steps.py'>]
DEBUG    root:init_helpers.py:102 Directory verified: /app/data/attachments
DEBUG    root:init_helpers.py:108 Saving screenshot to: /app/data/attachments/qa_edge_131.0.2903.48_error_message_appears_for_last_name.png
DEBUG    root:playwrightHelper.py:89 Scrolling to the top of the page.
DEBUG    root:init_helpers.py:114 Screenshot attached at: /app/data/attachments/qa_edge_131.0.2903.48_error_message_appears_for_last_name.png
DEBUG    pytest_bdd.scenario:scenario.py:146 Adding providers for fixture 'pytestbdd_stepimpl_then_I can see a dob error message Enter the date of birth': [<FixtureDef argname='pytestbdd_stepdef_then_I can see a dob error message {errorMessage}' scope='function' baseid='tests/test_find_a_patient_steps.py'>]
DEBUG    root:init_helpers.py:102 Directory verified: /app/data/attachments
DEBUG    root:init_helpers.py:108 Saving screenshot to: /app/data/attachments/qa_edge_131.0.2903.48_error_message_appears_for_dob.png
DEBUG    root:playwrightHelper.py:89 Scrolling to the top of the page.
DEBUG    root:init_helpers.py:114 Screenshot attached at: /app/data/attachments/qa_edge_131.0.2903.48_error_message_appears_for_dob.png