ERROR    root:init_helpers.py:114 Screenshot capture failed or file not found at: data/attachments/dev_chrome_130.0.6723.58_sign_in_should_pass.png