{
  "uid" : "e3de35d443502b5a",
  "name" : "Demographics: Multiple demographic matches shows an error that more than one result is found [Aidan-Smith-23/02/2020]",
  "fullName" : "/app/features/find_a_patient.feature:Demographics: Multiple demographic matches shows an error that more than one result is found",
  "historyId" : "1c8cb41f30fceb416baf4c1b8bdba2ab",
  "time" : {
    "start" : 1731061777667,
    "stop" : 1731061794253,
    "duration" : 16586
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert False == True\n +  where False = check_patient_multiple_results_found_message_exists(True)",
  "statusTrace" : "fixturefunc = <function step_assert_multiple_results_found_for_patient_message at 0x7f832c6f6ac0>\nrequest = <FixtureRequest for <Function test_demographics_multiple_demographic_matches_shows_an_error_that_more_than_one_result_is_found[Aidan-Smith-23/02/2020]>>\nkwargs = {}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\n.tox/py311/lib/python3.11/site-packages/_pytest/fixtures.py:898: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @then(\"I can see a message that more than one result was found\")\n    def step_assert_multiple_results_found_for_patient_message():\n        attach_screenshot(\"multiple_results_found_should_be_visible\")\n>       assert check_patient_multiple_results_found_message_exists(True) == True\nE       assert False == True\nE        +  where False = check_patient_multiple_results_found_message_exists(True)\n\ntests/test_find_a_patient_steps.py:211: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: assert False == True\n +  where False = check_patient_multiple_results_found_message_exists(True)",
    "statusTrace" : "fixturefunc = <function step_assert_multiple_results_found_for_patient_message at 0x7f832c6f6ac0>\nrequest = <FixtureRequest for <Function test_demographics_multiple_demographic_matches_shows_an_error_that_more_than_one_result_is_found[Aidan-Smith-23/02/2020]>>\nkwargs = {}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\n.tox/py311/lib/python3.11/site-packages/_pytest/fixtures.py:898: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @then(\"I can see a message that more than one result was found\")\n    def step_assert_multiple_results_found_for_patient_message():\n        attach_screenshot(\"multiple_results_found_should_be_visible\")\n>       assert check_patient_multiple_results_found_message_exists(True) == True\nE       assert False == True\nE        +  where False = check_patient_multiple_results_found_message_exists(True)\n\ntests/test_find_a_patient_steps.py:211: AssertionError",
    "steps" : [ {
      "name" : "Given I am on the find a patient by demographics page",
      "time" : {
        "start" : 1731061777668,
        "stop" : 1731061782480,
        "duration" : 4812
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "And I enter the mandatory patient details Aidan, Smith, and 23/02/2020",
      "time" : {
        "start" : 1731061782480,
        "stop" : 1731061782981,
        "duration" : 501
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "50b5a0883a02a2aa",
        "name" : "dev_edge_130.0.2849.80_add_mandatory_patient_information.png",
        "source" : "50b5a0883a02a2aa.png",
        "type" : "image/png",
        "size" : 51603
      } ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "When I click the search button",
      "time" : {
        "start" : 1731061782982,
        "stop" : 1731061783994,
        "duration" : 1012
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Then I can see a message that more than one result was found",
      "time" : {
        "start" : 1731061783995,
        "stop" : 1731061794253,
        "duration" : 10258
      },
      "status" : "failed",
      "statusMessage" : "assert False == True\n +  where False = check_patient_multiple_results_found_message_exists(True)",
      "statusTrace" : "AssertionError: assert False == True\n +  where False = check_patient_multiple_results_found_message_exists(True)\n",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "41cacc9e2892e43c",
        "name" : "dev_edge_130.0.2849.80_multiple_results_found_should_be_visible.png",
        "source" : "41cacc9e2892e43c.png",
        "type" : "image/png",
        "size" : 29862
      } ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "ebc279bd1ab56d6e",
      "name" : "log",
      "source" : "ebc279bd1ab56d6e.txt",
      "type" : "text/plain",
      "size" : 2174
    } ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "host",
    "value" : "192eb275bb20"
  }, {
    "name" : "thread",
    "value" : "1102-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest-bdd"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "feature",
    "value" : "Find a patient"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "dob",
    "value" : "23/02/2020"
  }, {
    "name" : "firstName",
    "value" : "Aidan"
  }, {
    "name" : "lastName",
    "value" : "Smith"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "e3de35d443502b5a.json",
  "parameterValues" : [ "23/02/2020", "Aidan", "Smith" ]
}